src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        [HttpPost]
        public JsonResult Listar(long IdCliente)
        {
            try
            {
                List<Beneficiario> beneficiarios = new BoBeneficiario().Pesquisa(IdCliente);             

                return Json(new
                {
                    Result = "OK",
                    Records = beneficiarios,
                    TotalRecordCount = beneficiarios.Count
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = ex.Message
                });
            }
        }


        [HttpPost]
        public JsonResult Salvar(List<Beneficiario> beneficiarios)
        {
            try
            {
                BoBeneficiario boBeneficiario = new BoBeneficiario();
                boBeneficiario.Salvar(beneficiarios);
                
                return Json(new
                {
                    Result = "OK"
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Result = "ERROR",
                    Message = ex.Message
                });
            }
        }
   
    }
}

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();

            if (bo.VerificarExistencia(0, model.CPF))
                ModelState.AddModelError("CPF", "CPF Informado já existe");

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                model.Id = bo.Incluir(new Cliente()
                {
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF
                });

                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();

            if (bo.VerificarExistencia(model.Id, model.CPF))
                ModelState.AddModelError("CPF", "CPF Informado já existe");

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    CPF = model.CPF
                });

                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    CPF = cliente.CPF
                };
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var beneficiarios = null;
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';

        var urlBeneficiarioSalvar = '@Url.Action("Salvar", "Beneficiario", new { area = "" })';
        var urlBeneficiarioExclusao = '@Url.Action("Excluir", "Beneficiario", new { area = "" })';
        var urlBeneficiarioListar = '@Url.Action("Listar", "Beneficiario", new { area = "" })';
        var urlBeneficiarioBuscarId = '@Url.Action("BuscarId", "Beneficiario", new { area = "" })';
    </script>

    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/listBeneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")
@Html.Partial("Beneficiarios")

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Beneficiarios.cshtml
<div class="modal fade" id="addBeneficiarios" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <span class="modal-title h4" id="exampleModalLabel">Beneficiários</span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="formBeneficiario" method="post">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>CPF:</label>
                                <input required="required" type="text" class="form-control" id="CPFBeneficiario" name="CPFBeneficiario" maxlength="14">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <label>Nome:</label>
                                    <input required="required" type="text" class="form-control" id="NomeBeneficiario" name="NomeBeneficiario" maxlength="50">
                                    <input id="IdBeneficiario" type="hidden" />
                                    
                                </div>
                                <div>
                                    <button id="btnBeneficiarioIncluir" class="btn btn-sm btn-success" 
                                            style="
                                            /* display: inline-block; */
                                            /* vertical-align: bottom; */
                                            /* float: none; */
                                            position: absolute;
                                            bottom: 0.2em;
                                        ">
                                        Salvar
                                    </button>
                                    <input id="submit-hidden" type="submit" style="display: none" />
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-md-12">
                        <table id="gridBeneficiario" class="table"></table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
               
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
@{ 
    TempData.Keep("Beneficiarios");
}

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
                <input id="Id" name="Id" type="hidden" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="CPF">CPF:</label>
                <input required="required" type="text" class="form-control" id="CPF" name="CPF" placeholder="___.___.___-__" maxlength="14">
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                    <option value="TO">Tocantins</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-left">
                <button id="btnBeneficiarios" disabled="disabled" type="button" class="btn btn-default" data-toggle="modal" data-target="#addBeneficiarios">
                    Beneficiários
                </button>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>
</form>

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/clientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

src/FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
    <script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>

@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class = "btn btn-sm btn-primary pull-right" })

<table id="gridClientes" class="table"></table>